import { MarkerType } from "@xyflow/react";
import { Zap, Globe, Database, Cpu, Bell } from "lucide-react";
import { NodeCategory, NodeDetails, SavedFlow } from "@/app/types/flow";

export const STORAGE_KEY = "apiflow-testing-workflows-v4";

export const NODE_CATEGORY_CONFIGS = [
  { id: "api" as const, name: "API Request", icon: Globe },
  { id: "trigger" as const, name: "Trigger / Webhook", icon: Zap },
  { id: "transform" as const, name: "Data Transform", icon: Cpu },
  { id: "database" as const, name: "Database Query", icon: Database },
  { id: "action" as const, name: "Action / Alert", icon: Bell },
];

export function defaultNodeData(
  label: string,
  category: NodeCategory = "api",
  stepNum?: number
): NodeDetails {
  return {
    nodeNumber: stepNum,
    label,
    category,
    method: category === "api" ? "POST" : undefined,
    baseUrl: "https://api.example.com",
    endpoint: category === "api" ? "/api/v1/step" : undefined,
    owner: "Engineering",
    status: "In progress",
    priority: "High",
    description: "Orchestrates API calls and workflow verification.",
    expectedStatus: 200,
    requestBody: '{\n  "test": true\n}',
    customFields: [
      { id: "f-1", label: "Content-Type", value: "application/json" },
    ],
  };
}

export const starterFlows: SavedFlow[] = [
  {
    id: "flow-ecommerce-test",
    name: "E-commerce API Test",
    description: "6-step sequential API workflow verification: Auth -> Profile -> Catalog -> Cart -> Checkout -> Logout.",
    updatedAt: Date.now(),
    nodes: [
      {
        id: "node-1",
        type: "apiStep",
        position: { x: 60, y: 180 },
        data: {
          nodeNumber: 1,
          label: "Login API",
          category: "api",
          method: "POST",
          baseUrl: "https://api.ecommerce.com",
          endpoint: "/login",
          owner: "Auth Team",
          status: "Completed",
          priority: "Critical",
          description: "Submits credentials and returns user access token.",
          authToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
          expectedStatus: 200,
          requestBody: '{\n  "email": "test@test.com",\n  "password": "secret"\n}',
          customFields: [
            { id: "cf-1", label: "Content-Type", value: "application/json" },
          ],
        },
      },
      {
        id: "node-2",
        type: "apiStep",
        position: { x: 380, y: 180 },
        data: {
          nodeNumber: 2,
          label: "Profile API",
          category: "api",
          method: "GET",
          baseUrl: "https://api.ecommerce.com",
          endpoint: "/profile",
          owner: "User Core",
          status: "Completed",
          priority: "High",
          description: "Fetches user profile, permissions, and tenant metadata.",
          expectedStatus: 200,
          customFields: [
            { id: "cf-2", label: "Authorization", value: "Bearer {{token}}" },
          ],
        },
      },
      {
        id: "node-3",
        type: "apiStep",
        position: { x: 700, y: 180 },
        data: {
          nodeNumber: 3,
          label: "Products API",
          category: "api",
          method: "GET",
          baseUrl: "https://api.ecommerce.com",
          endpoint: "/products",
          owner: "Catalog Team",
          status: "Completed",
          priority: "High",
          description: "Queries active catalog listings with pagination parameters.",
          expectedStatus: 200,
          customFields: [
            { id: "cf-3", label: "Cache-Control", value: "no-cache" },
            { id: "cf-3b", label: "limit", value: "20" },
          ],
        },
      },
      {
        id: "node-4",
        type: "apiStep",
        position: { x: 1020, y: 180 },
        data: {
          nodeNumber: 4,
          label: "Cart API",
          category: "api",
          method: "POST",
          baseUrl: "https://api.ecommerce.com",
          endpoint: "/cart",
          owner: "Checkout Team",
          status: "Not started",
          priority: "Medium",
          description: "Adds featured SKU to customer cart session.",
          expectedStatus: 200,
          requestBody: '{\n  "sku": "PROD-101",\n  "quantity": 1\n}',
          customFields: [
            { id: "cf-4", label: "Content-Type", value: "application/json" },
          ],
        },
      },
      {
        id: "node-5",
        type: "apiStep",
        position: { x: 1340, y: 180 },
        data: {
          nodeNumber: 5,
          label: "Checkout API",
          category: "api",
          method: "POST",
          baseUrl: "https://api.ecommerce.com",
          endpoint: "/checkout",
          owner: "Payment Core",
          status: "Not started",
          priority: "Critical",
          description: "Creates and confirms checkout payment intent.",
          expectedStatus: 200,
          requestBody: '{\n  "paymentMethod": "mock_card",\n  "currency": "USD"\n}',
          customFields: [],
        },
      },
      {
        id: "node-6",
        type: "apiStep",
        position: { x: 1660, y: 180 },
        data: {
          nodeNumber: 6,
          label: "Logout API",
          category: "api",
          method: "POST",
          baseUrl: "https://api.ecommerce.com",
          endpoint: "/logout",
          owner: "Auth Team",
          status: "Not started",
          priority: "Low",
          description: "Invalidates JWT session and writes audit entry.",
          expectedStatus: 200,
          customFields: [],
        },
      },
    ],
    edges: [
      {
        id: "e-1-2",
        source: "node-1",
        target: "node-2",
        type: "smoothstep",
        animated: true,
        style: { stroke: "#BAFF39", strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: "#BAFF39" },
      },
      {
        id: "e-2-3",
        source: "node-2",
        target: "node-3",
        type: "smoothstep",
        animated: true,
        style: { stroke: "#BAFF39", strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: "#BAFF39" },
      },
      {
        id: "e-3-4",
        source: "node-3",
        target: "node-4",
        type: "smoothstep",
        animated: true,
        style: { stroke: "#BAFF39", strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: "#BAFF39" },
      },
      {
        id: "e-4-5",
        source: "node-4",
        target: "node-5",
        type: "smoothstep",
        animated: true,
        style: { stroke: "#BAFF39", strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: "#BAFF39" },
      },
      {
        id: "e-5-6",
        source: "node-5",
        target: "node-6",
        type: "smoothstep",
        animated: true,
        style: { stroke: "#BAFF39", strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: "#BAFF39" },
      },
    ],
  },
  {
    id: "flow-stripe-webhook",
    name: "Stripe Webhook & DB Sync",
    description: "Ingests payment webhooks, parses event data, and synchronizes subscriber tier in PostgreSQL.",
    updatedAt: Date.now() - 3600000,
    nodes: [
      {
        id: "sw-1",
        type: "apiStep",
        position: { x: 80, y: 180 },
        data: {
          nodeNumber: 1,
          label: "Stripe Webhook Listener",
          category: "trigger",
          method: "POST",
          baseUrl: "https://api.stripe.com",
          endpoint: "/webhooks/charge-succeeded",
          owner: "Alex R.",
          status: "Completed",
          priority: "Critical",
          description: "Listens for payment intent succeeded events and verifies cryptographic signature.",
          customFields: [
            { id: "scf-1", label: "WebhookSecret", value: "whsec_live_9a87bf..." },
          ],
        },
      },
      {
        id: "sw-2",
        type: "apiStep",
        position: { x: 420, y: 180 },
        data: {
          nodeNumber: 2,
          label: "Transform & Normalize",
          category: "transform",
          endpoint: "data.customer.tier",
          owner: "Data Team",
          status: "Completed",
          priority: "High",
          description: "Extracts customer UUID and normalizes payload according to unified schema.",
          customFields: [],
        },
      },
      {
        id: "sw-3",
        type: "apiStep",
        position: { x: 760, y: 180 },
        data: {
          nodeNumber: 3,
          label: "Upsert PostgreSQL User",
          category: "database",
          method: "POST",
          endpoint: "db.users.upsert()",
          owner: "Backend",
          status: "In progress",
          priority: "High",
          description: "Updates user subscription record in the transactions ledger.",
          customFields: [],
        },
      },
      {
        id: "sw-4",
        type: "apiStep",
        position: { x: 1100, y: 180 },
        data: {
          nodeNumber: 4,
          label: "Slack Alert & Receipt",
          category: "action",
          method: "POST",
          endpoint: "https://hooks.slack.com/services/...",
          owner: "Growth Team",
          status: "Not started",
          priority: "Medium",
          description: "Notifies #sales-wins channel and sends confirmation receipt.",
          customFields: [],
        },
      },
    ],
    edges: [
      {
        id: "e-sw-1-2",
        source: "sw-1",
        target: "sw-2",
        type: "smoothstep",
        animated: true,
        style: { stroke: "#BAFF39", strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: "#BAFF39" },
      },
      {
        id: "e-sw-2-3",
        source: "sw-2",
        target: "sw-3",
        type: "smoothstep",
        animated: true,
        style: { stroke: "#BAFF39", strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: "#BAFF39" },
      },
      {
        id: "e-sw-3-4",
        source: "sw-3",
        target: "sw-4",
        type: "smoothstep",
        animated: true,
        style: { stroke: "#BAFF39", strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: "#BAFF39" },
      },
    ],
  },
  {
    id: "flow-auth-test",
    name: "Authentication Flow",
    description: "3-step authentication verification: Login -> Token Verify -> Session Profile.",
    updatedAt: Date.now() - 1800000,
    nodes: [
      {
        id: "auth-1",
        type: "apiStep",
        position: { x: 120, y: 180 },
        data: {
          nodeNumber: 1,
          label: "Login API",
          category: "api",
          method: "POST",
          baseUrl: "https://api.ecommerce.com",
          endpoint: "/auth/login",
          owner: "Auth Team",
          status: "Completed",
          priority: "Critical",
          description: "Authenticates credentials and returns JWT bearer token.",
          expectedStatus: 200,
          requestBody: '{\n  "email": "alex@company.com",\n  "password": "••••••••"\n}',
          customFields: [
            { id: "acf-1", label: "Content-Type", value: "application/json" },
          ],
        },
      },
      {
        id: "auth-2",
        type: "apiStep",
        position: { x: 460, y: 180 },
        data: {
          nodeNumber: 2,
          label: "Verify Token",
          category: "api",
          method: "GET",
          baseUrl: "https://api.ecommerce.com",
          endpoint: "/auth/verify",
          owner: "Security Team",
          status: "Completed",
          priority: "High",
          description: "Validates cryptographic signature and claims expiration.",
          expectedStatus: 200,
          customFields: [
            { id: "acf-2", label: "Authorization", value: "Bearer {{token}}" },
          ],
        },
      },
      {
        id: "auth-3",
        type: "apiStep",
        position: { x: 800, y: 180 },
        data: {
          nodeNumber: 3,
          label: "Tenant Profile",
          category: "api",
          method: "GET",
          baseUrl: "https://api.ecommerce.com",
          endpoint: "/users/me",
          owner: "User Core",
          status: "In progress",
          priority: "High",
          description: "Retrieves tenant workspace profile and user permissions.",
          expectedStatus: 200,
          customFields: [
            { id: "acf-3", label: "Authorization", value: "Bearer {{token}}" },
          ],
        },
      },
    ],
    edges: [
      {
        id: "e-auth-1-2",
        source: "auth-1",
        target: "auth-2",
        type: "smoothstep",
        animated: true,
        style: { stroke: "#BAFF39", strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: "#BAFF39" },
      },
      {
        id: "e-auth-2-3",
        source: "auth-2",
        target: "auth-3",
        type: "smoothstep",
        animated: true,
        style: { stroke: "#BAFF39", strokeWidth: 2 },
        markerEnd: { type: MarkerType.ArrowClosed, color: "#BAFF39" },
      },
    ],
  },
];
